### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by wovalle** [wovalle/fireorm#1]
# FireORM official roadmap!
Since [I'm](https://github.com/wovalle) the only developer working in FireORM at the moment, I use this issue to track what to do with this project :)

**Collaborations are welcome!** If you want to start working on a feature that is listed below, please create another issue to start the discussion. This issue is only meant to be used as a placeholder.

## v1 roadmap
- [x] Improvements in api documentation #78
- [x] Support for methods (and getters/setters) in models
- [x] Integration tests with real firestore db #31
- [x] Transactions support
- [x] OrderBy #30
- [x] Limit #18 
- [ ] Stricter typescript rules
- [ ] Better error handling (and custom errors)
- [x] Lazy subcollections (initialize subcollections without having to query the parent collection first) #51 
- [ ] Collection Group Queries

## Next major
- [ ] Pagination
- [ ] Firestore events subscription/dispatching support
- [ ] Relationships (1:1, 1:n, n:n, eager, lazy) #32
- [ ] Firebase js client support (probably)
- [ ] Increase the compatibility with Raw Firestore Documents

## Wishlist
- [ ] Javascript support
- [ ] Browser support
- [ ] Firebase Realtime database support
- [ ] Investigate if models can be enforced with db rules (cli project)
- [ ] (cli) Migrations
- [ ] Change tracking (instead of updating the entire document, just update the keys that changed)
- [ ] Custom decorators like @createdOnField, @updatedOnField
- [ ] Custom hooks? onCreate, onUpdate, onDelete, onRead
- [ ] (cli) Indexes management: throw custom errors when trying to do range filters for non-indexes for non indexed fields, creation and deletion of indexes.
